name: on-github-pages

on:
  push:
    branches: ["master"]

  workflow_dispatch:

permissions:
  contents: write 
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9  # stable
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32  # v2

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@23ee8ab6b7397851bc11705bcdf46f2519ea0285  # v1.9.0

      - name: Install Dioxus-CLI
        shell: bash
        run: cargo binstall dioxus-cli --version 0.7.9 --no-confirm

      - name: Build Project
        shell: bash
        run: |
          cd sqlx-repo-ui/
          ASSET_PREFIX="sqlx-repo" dx build --release
          cd ../target/dx/sqlx-repo-ui/release/web/public
          sed -i 's#/assets/#/sqlx-repo/assets/#g' index.html
          sed -i 's#/assets/#/sqlx-repo/assets/#g' assets/sqlx-repo-ui-*.js
          cp ./index.html ./404.html

      - name: Deploy Project
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f  # v4
        with:
          branch: gh-pages
          folder: target/dx/sqlx-repo-ui/release/web/public
